let state={clips:[],runs:[],actions:[],cameras:[],discovery:{}},token='',lastSnapshot='',category='',camera='',filter='',caseId='',editingCase=null;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time=s=>`${Math.floor(s/60).toString().padStart(2,'0')}:${(s%60).toFixed(s%1?1:0).padStart(2,'0')}`;
const link=c=>`https://www.youtube.com/watch?v=${c.video}&t=${Math.floor(c.start)}s`;
function toast(msg){$('#toast').textContent=msg;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',6000)}
async function post(url,data){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-Local-Token':token},body:JSON.stringify(data)});const x=await r.json();if(!r.ok)throw Error(x.error);return x}
async function refresh(){try{const r=await fetch('/api/state');if(!r.ok)throw Error('Niet verbonden');const next=await r.json();const snapshot=JSON.stringify(next);if(snapshot===lastSnapshot)return;lastSnapshot=snapshot;state=next;token=state.token;render()}catch(e){$('#status').textContent='App niet bereikbaar. Start de lokale engine opnieuw.'}}
function visible(){return state.clips.filter(c=>(!caseId||c.client===caseId)&&(!category||c.action===category)&&(!camera||c.camera===camera)&&(!filter||`${c.title} ${c.description} ${c.action} ${c.camera}`.toLowerCase().includes(filter)))}
function render(){const d=state.discovery,clips=visible(),caseData=state.clients?.find(c=>c.id===caseId),runs=state.runs.filter(r=>!caseId||r.client===caseId),active=runs.find(r=>['queued','running'].includes(r.status));
$('#case-list').innerHTML=(state.clients||[]).filter(c=>c.id!=='__library__').map(c=>`<button data-case="${esc(c.id)}" class="${caseId===c.id?'active':''}">${esc(c.name)}</button>`).join('');$('#case-edit').hidden=!caseId;$('#case-run').hidden=!caseId;$('#case-run').disabled=!!active;$('#pause').hidden=!!caseId;$('#title').textContent=caseData?.name||category||'Alle fragmenten';$('#categories').innerHTML=['',...state.actions].map(a=>`<button data-category="${esc(a)}" class="${a===category?'active':''}">${esc(a||'Alle fragmenten')} <small>${state.clips.filter(c=>(!caseId||c.client===caseId)&&(!a||c.action===a)).length}</small></button>`).join('');
$('#total').textContent=`${clips.length} fragmenten · ${caseId?'klantgericht':d.enabled?'automatisch actief':'gepauzeerd'}`;
$('#status').textContent=active?.message||(caseId?'':d.pause_reason)||runs[0]?.message||'De engine ontdekt zelfstandig nieuwe bewegingen.';
$('#next').textContent=caseId?'Deze case gebruikt de website, oude video’s en jouw notities.':d.enabled?`Volgende ronde: ${new Date(d.next_run*1000).toLocaleString('nl-NL')} · maximaal ${d.max_analyses} nieuwe analyses`:'Zet de engine aan om zonder zoekopdracht nieuwe fragmenten te verzamelen.';
$('#pause').textContent=d.enabled?'Pauzeren':'Automatisch starten';
$('#camera').innerHTML='<option value="">Alle camerabewegingen</option>'+state.cameras.map(c=>`<option ${c===camera?'selected':''}>${esc(c)}</option>`).join('');
$('#results').innerHTML=clips.length?clips.map((c,i)=>`<div class="row"><span class="number">${String(i+1).padStart(2,'0')}</span><div><a href="${link(c)}" target="_blank" rel="noreferrer">${link(c)}</a><small>${time(c.start)}–${time(c.end)} · ${esc(c.title)}</small><small class="tag">${esc(c.action)}</small><small class="tag">${esc(c.camera)}</small></div><button data-play="${c.id}">Bekijk</button></div>`).join(''):'<div class="empty">Hier staan nog geen fragmenten.<br>De engine vult de categorieën tijdens volgende zoekrondes.</div>';
const opened=new Set([...document.querySelectorAll('details[open]')].map(x=>x.dataset.run));
$('#costs').innerHTML=`<div class="costhero">$${runs.reduce((n,r)=>n+r.cost,0).toFixed(5)} <small>totaal berekend Gemini-verbruik</small></div><p>Automatisch ontdekken, laatste 24 uur: $${(d.spent_24h||0).toFixed(5)} / $${d.daily_budget}</p><p class="muted">Standaardtarieframing in USD, ${esc(state.rates.date)}. Geen bevestigde factuur. Ronden zonder resultaat en onbekend verbruik blijven zichtbaar.</p>`+runs.map(r=>`<details data-run="${r.id}" ${opened.has(r.id)?'open':''}><summary>${new Date(r.created*1000).toLocaleString('nl-NL')} · ${r.count} clips · $${r.cost.toFixed(5)}${r.unknown_cost?' + onbekend verbruik':''}</summary><p>${esc(r.message)}</p><p>Per nieuw fragment: ${r.per_clip===null?'geen resultaten':('$'+r.per_clip.toFixed(6))}</p><table><thead><tr><th>Aanroep</th><th>Verbruik</th><th>USD</th></tr></thead><tbody>${r.calls.map(x=>`<tr><td>${esc(x.provider)} / ${esc(x.purpose)}<br><small>${esc(x.status)}</small></td><td>${x.provider==='youtube'?'1 request':`${x.usage.total_input_tokens??'?'} in / ${x.usage.total_output_tokens??'?'} uit / ${x.usage.total_thought_tokens??'?'} denk`}</td><td>${x.cost===null?'onbekend':x.cost.toFixed(6)}</td></tr>`).join('')}</tbody></table></details>`).join('')+'<h3>Kosten per fragment</h3><table><thead><tr><th>Fragment</th><th>Direct USD</th><th>Gedeeld USD</th><th>Totaal USD</th></tr></thead><tbody>'+clips.map(c=>`<tr><td><a href="${link(c)}" target="_blank" rel="noreferrer">${esc(c.video)} · ${time(c.start)}</a></td><td>${(c.direct_cost||0).toFixed(6)}</td><td>${(c.shared_cost||0).toFixed(6)}</td><td>${(c.cost||0).toFixed(6)}${c.unknown_cost?' + ?':''}</td></tr>`).join('')+'</tbody></table>';
}
$('#categories').onclick=e=>{const b=e.target.closest('[data-category]');if(b){category=b.dataset.category;render()}};
$('#camera').onchange=e=>{camera=e.target.value;render()};$('#filter').oninput=e=>{filter=e.target.value.toLowerCase();render()};
$('#settings').onclick=()=>{for(const [k,v]of Object.entries(state.discovery)){const f=$('#form').elements.namedItem(k);if(f){if(f.type==='checkbox')f.checked=v;else f.value=v}}$('#editor').showModal()};$('#close').onclick=()=>$('#editor').close();
$('#form').onsubmit=async e=>{e.preventDefault();try{const data=Object.fromEntries(new FormData(e.target));data.enabled=e.target.elements.enabled.checked;await post('/api/discovery',data);$('#editor').close();await refresh();toast('Instellingen opgeslagen.')}catch(e){toast(e.message)}};
$('#pause').onclick=async()=>{try{await post('/api/discovery',{enabled:!state.discovery.enabled});await refresh()}catch(e){toast(e.message)}};
$('#search').onclick=async()=>{try{await post('/api/discover',{});$('#editor').close();await refresh()}catch(e){toast(e.message)}};
$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(visible().map(c=>`${link(c)} — ${time(c.start)}–${time(c.end)}`).join('\n'));toast('Alle zichtbare links gekopieerd.')}catch{toast('Kopiëren geblokkeerd door de browser.')}};
$('.tabs').onclick=e=>{if(!e.target.dataset.tab)return;document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('selected',b===e.target));$('#results').hidden=e.target.dataset.tab!=='results';$('#filters').hidden=e.target.dataset.tab!=='results';$('#costs').hidden=e.target.dataset.tab!=='costs'};
$('#results').onclick=e=>{const c=state.clips.find(c=>c.id===e.target.dataset.play);if(c){$('#embed').innerHTML=`<iframe title="Geselecteerd fragment" src="https://www.youtube.com/embed/${c.video}?start=${Math.floor(c.start)}&end=${Math.ceil(c.end)}&autoplay=1" allow="autoplay; encrypted-media" allowfullscreen></iframe><p><a href="${link(c)}" target="_blank" rel="noreferrer">Open op YouTube</a> · ${time(c.start)}–${time(c.end)}</p>`;$('#player').showModal()}};
$('#player-close').onclick=()=>$('#player').close();$('#player').addEventListener('close',()=>$('#embed').innerHTML='');
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'list_movement_links',description:'Lees alle zichtbare gecategoriseerde fragmentlinks.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input)=>{if(!input||Object.keys(input).length)throw Error('Geen parameters toegestaan.');await refresh();return visible().map(c=>({url:link(c),start:c.start,end:c.end,action:c.action,camera:c.camera}))}})}catch{}}
refresh();setInterval(refresh,3000);

function resetFilters(){category='';camera='';filter='';$('#filter').value=''}
$('#general').onclick=()=>{caseId='';resetFilters();render()};
$('#case-list').onclick=e=>{const b=e.target.closest('[data-case]');if(b){caseId=b.dataset.case;resetFilters();render()}};
function openCase(c){editingCase=c?.id||null;$('#case-form').reset();if(c)for(const [k,v]of Object.entries(c)){const f=$('#case-form').elements.namedItem(k);if(f)f.value=v}$('#case-upload-status').textContent="Maximaal 100 MB. Referentievideo's worden bij zoeken naar Gemini gestuurd.";$('#case-editor').showModal()}
$('#newcase').onclick=()=>openCase(null);$('#case-edit').onclick=()=>openCase(state.clients.find(c=>c.id===caseId));$('#case-close').onclick=()=>$('#case-editor').close();
$('#case-form').onsubmit=async e=>{e.preventDefault();try{const d=Object.fromEntries(new FormData(e.target));d.id=editingCase;d.weekly=false;const r=await post('/api/client',d);caseId=r.id;resetFilters();if(e.submitter?.name==='run')await post('/api/run',{client:caseId});$('#case-editor').close();await refresh();render();toast('Case opgeslagen.')}catch(e){toast(e.message)}};
$('#case-run').onclick=async()=>{try{await post('/api/run',{client:caseId});await refresh()}catch(e){toast(e.message)}};
$('#case-upload').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>100*1024*1024)return toast('Maximaal 100 MB.');try{const r=await fetch('/api/upload',{method:'POST',headers:{'Content-Type':f.type,'X-Local-Token':token},body:f});const x=await r.json();if(!r.ok)throw Error(x.error);const area=$('#case-form').elements.videos;area.value+=(area.value?'\n':'')+x.reference;$('#case-upload-status').textContent=f.name+' toegevoegd. Sla de case op.'}catch(e){toast(e.message)}e.target.value=''};
